version: 2

project_name: dio

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: dio
    main: ./cmd/dio
    binary: dio
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive
  - artifacts: binary

signs:
  - cmd: cosign
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --yes
      - --output-certificate=${certificate}
      - --output-signature=${signature}
      - ${artifact}
    artifacts: checksum
    output: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: yuxiangchang
    name: docker-image-optimiser

